spin_manifest_version = "1"
authors = ["Justin Pflueger <justin.pflueger@fermyon.com>"]
description = "An example app using the Spin SDK and Key-Value backed storage"
name = "spin-kv-example"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "spin-kv-example"
source = "target/wasm32-wasi/release/spin_kv_example.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
